INHERIT: zi_mkdocs/global.yml

site_name: LabOne Q Applications Library
docs_dir: sources
site_dir: ../site

watch:
- ../src/laboneq_applications
- zi_mkdocs

nav:
- Home: index.md

plugins:
  literate-nav:
    nav_file: "index.md"
    implicit_index: true
  macros:
    include_dir: ""
  mkdocstrings:
    handlers:
      python:
        import: [
          "https://docs.zhinst.com/labone_q_user_manual/objects.inv"
        ]
