site_name: LabOne Q Applications Library
docs_dir: sources
site_dir: ../site

watch:
  - ../src/laboneq_applications

nav:
  - Home: index.md
  - How-to Guides:
      - how-to-guides/index.md
      - Amplitude Rabi: how-to-guides/sources/01_superconducting_qubits/01_workflows/amplitude_rabi.ipynb
      - Ramsey interferometry: how-to-guides/sources/01_superconducting_qubits/01_workflows/ramsey.ipynb
      - Amplitude Fine: how-to-guides/sources/01_superconducting_qubits/01_workflows/amplitude_fine.ipynb
      - Dispersive Shift: how-to-guides/sources/01_superconducting_qubits/01_workflows/dispersive_shift.ipynb
      - Echo: how-to-guides/sources/01_superconducting_qubits/01_workflows/echo.ipynb
      - IQ blobs: how-to-guides/sources/01_superconducting_qubits/01_workflows/iq_blobs.ipynb
      - Lifetime measurement: how-to-guides/sources/01_superconducting_qubits/01_workflows/lifetime_measurement.ipynb
      - Qubit spectroscopy: how-to-guides/sources/01_superconducting_qubits/01_workflows/qubit_spectroscopy.ipynb
      - Resonator Spectroscopy: how-to-guides/sources/01_superconducting_qubits/01_workflows/resonator_spectroscopy.ipynb
      - Resonator Spectroscopy DC bias: how-to-guides/sources/01_superconducting_qubits/01_workflows/resonator_spectroscopy_dcbias.ipynb
      - Raw Time Traces for Optimal Readout Weights: how-to-guides/sources/01_superconducting_qubits/01_workflows/time_traces.ipynb
      - OpenQASM:
        - how-to-guides/sources/04_qasm/01_VQE_Qiskit.ipynb
        - how-to-guides/sources/04_qasm/02_RandomizedBenchmarking_from_Qiskit.ipynb
  - Tutorials:
      - tutorials/index.md
      - Experiment Workflows: tutorials/sources/experiment_workflows.ipynb
      - Quantum Operations: tutorials/sources/quantum_operations.ipynb
      - Workflow:
          - tutorials/workflow/index.md
          - Build a workflow: tutorials/workflow/sources/build_workflow.ipynb
          - Options: tutorials/workflow/sources/options.ipynb
          - Variables and references: tutorials/workflow/sources/workflow_language.ipynb
      - Tasks: tutorials/sources/tasks.ipynb
      - Logbooks: tutorials/sources/logbooks.ipynb
  - Release Notes: release_notes.md
  - API Reference:
      - reference/index.md
      - core:
          - reference/core/index.md
          - build_experiment: reference/core/build_experiment.md
          - quantum_operations: reference/core/quantum_operations.md
          - validation: reference/core/validation.md
      - experiments:
          - reference/experiments/index.md
          - resonator_spectroscopy: reference/experiments/resonator_spectroscopy.md
          - resonator_spectroscopy_amplitude: reference/experiments/resonator_spectroscopy_amplitude.md
          - qubit_spectroscopy: reference/experiments/qubit_spectroscopy.md
          - qubit_spectroscopy_amplitude: reference/experiments/qubit_spectroscopy_amplitude.md
          - amplitude_rabi: reference/experiments/amplitude_rabi.md
          - ramsey: reference/experiments/ramsey.md
          - lifetime_measurement: reference/experiments/lifetime_measurement.md
          - echo: reference/experiments/echo.md
          - drag_q_scaling: reference/experiments/drag_q_scaling.md
          - amplitude_fine: reference/experiments/amplitude_fine.md
          - dispersive_shift: reference/experiments/dispersive_shift.md
          - iq_blobs: reference/experiments/iq_blobs.md
          - time_traces: reference/experiments/time_traces.md
          - options: reference/experiments/options.md
      - analysis:
          - reference/analysis/index.md
          - resonator_spectroscopy: reference/analysis/resonator_spectroscopy.md
          - qubit_spectroscopy: reference/analysis/qubit_spectroscopy.md
          - amplitude_rabi: reference/analysis/amplitude_rabi.md
          - ramsey: reference/analysis/ramsey.md
          - lifetime_measurement: reference/analysis/lifetime_measurement.md
          - echo: reference/analysis/echo.md          
          - drag_q_scaling: reference/analysis/drag_q_scaling.md
          - amplitude_fine: reference/analysis/amplitude_fine.md
          - dispersive_shift: reference/analysis/dispersive_shift.md
          - iq_blobs: reference/analysis/iq_blobs.md
          - time_traces: reference/analysis/time_traces.md
          - calibration_traces_rotation: reference/analysis/calibration_traces_rotation.md
          - fitting_helpers: reference/analysis/fitting_helpers.md
          - plotting_helpers: reference/analysis/plotting_helpers.md
      - contrib:
          - reference/contrib/index.md
          - experiments:
              - reference/contrib/experiments/index.md
              - amplitude_rabi_chevron: reference/contrib/experiments/amplitude_rabi_chevron.md
              - time_rabi: reference/contrib/experiments/time_rabi.md
              - time_rabi_chevron: reference/contrib/experiments/time_rabi_chevron.md
              - signal_propagation_delay: reference/contrib/experiments/signal_propagation_delay.md
              - single_qubit_randomized_benchmarking: reference/contrib/experiments/single_qubit_randomized_benchmarking.md
              - spin_locking: reference/contrib/experiments/spin_locking.md
          - analysis:
              - reference/contrib/analysis/index.md
              - amplitude_rabi_chevron: reference/contrib/analysis/amplitude_rabi_chevron.md
              - time_rabi: reference/contrib/analysis/time_rabi.md
              - time_rabi_chevron: reference/contrib/analysis/time_rabi_chevron.md
              - signal_propagation_delay: reference/contrib/analysis/signal_propagation_delay.md
              - single_qubit_randomized_benchmarking: reference/contrib/analysis/single_qubit_randomized_benchmarking.md
      - qpu_types:
          - reference/qpu_types/index.md
          - qpu: reference/qpu_types/qpu.md
          - tunable_transmon: reference/qpu_types/tunable_transmon.md
      - tasks:
          - reference/tasks/index.md
          - parameter_updating: reference/tasks/parameter_updating.md
      - testing: reference/testing.md
      - typing: reference/typing.md
      - dsl: reference/dsl.md

plugins:
  mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, false]
    handlers:
      python:
        # TODO: The commented out link below is for the public release.
        #       Do we still need it? Or does the release via the documentation
        #       hub make it obsolete?
        # import: ["https://docs.zhinst.com/labone_q_user_manual/objects.inv"]
        import: ["http://qccs.pages.zhinst.com/qccs/manual/objects.inv"]
  mkdocs-jupyter:
    execute: true
  spellcheck:
    known_words: ../known_words.txt
  zhinst-standalone:
    projects:
      - qccs/qccs
