site_name: LabOne Q Applications Library
docs_dir: sources
site_dir: ../site

watch:
  - ../src/laboneq_applications

nav:
    - Home: index.md
    - Tutorials:
      - tutorials/index.md
      - Defining the Experimental Setup: tutorials/sources/getting_started.ipynb
      - Experiment Workflows: tutorials/sources/experiment_workflows.ipynb
      - Quantum Operations: tutorials/sources/quantum_operations.ipynb
      - Tasks: tutorials/sources/tasks.ipynb
      - Logbooks: tutorials/sources/logbooks.ipynb
    - How-to Guides:
        - how-to-guides/index.md
        - Superconducting Qubits:
            - how-to-guides/sources/01_superconducting_qubits/index.md
            - Pulse Sequences:
                - Tune-up:
                    - how-to-guides/sources/01_superconducting_qubits/02_pulse_sequences/01_tuneup/00_readout_raw_data.ipynb
                    - how-to-guides/sources/01_superconducting_qubits/02_pulse_sequences/01_tuneup/01_cw_resonator_spec_shfsg_shfqa_shfqc.ipynb
                    - how-to-guides/sources/01_superconducting_qubits/02_pulse_sequences/01_tuneup/01_spec_uhfqa_hdawg.ipynb
                    - how-to-guides/sources/01_superconducting_qubits/02_pulse_sequences/01_tuneup/02_pulsed_resonator_spec_shfsg_shfqa_shfqc.ipynb
                    - how-to-guides/sources/01_superconducting_qubits/02_pulse_sequences/01_tuneup/03_resonator_spec_vs_power_shfsg_shfqa_shfqc.ipynb
                    - how-to-guides/sources/01_superconducting_qubits/02_pulse_sequences/01_tuneup/04_propagation_delay.ipynb
                    - how-to-guides/sources/01_superconducting_qubits/02_pulse_sequences/01_tuneup/05_qubit_spectroscopy.ipynb
                    - how-to-guides/sources/01_superconducting_qubits/02_pulse_sequences/01_tuneup/06_amplitude_rabi.ipynb
                    - how-to-guides/sources/01_superconducting_qubits/02_pulse_sequences/01_tuneup/07_ramsey.ipynb
                    - how-to-guides/sources/01_superconducting_qubits/02_pulse_sequences/01_tuneup/08_e-f_transition_spectroscopy_shfsg_shfqc.ipynb
                    - how-to-guides/sources/01_superconducting_qubits/02_pulse_sequences/01_tuneup/09_e-f_gate_tuneup_shfsg_shfqc.ipynb
                    - how-to-guides/sources/01_superconducting_qubits/02_pulse_sequences/01_tuneup/10_CR_gate_tuneup_shfsg_shfqc.ipynb
                    - how-to-guides/sources/01_superconducting_qubits/02_pulse_sequences/01_tuneup/11_readoutweight_calibration_shfsg_shfqa_shfqc.ipynb
                    - how-to-guides/sources/01_superconducting_qubits/02_pulse_sequences/01_tuneup/12_length_rabi_experiment_shfsg_shfqa_shfqc_hdawg.ipynb
                    - how-to-guides/sources/01_superconducting_qubits/02_pulse_sequences/01_tuneup/13_T1_experiment_shfsg_shfqa_shfqc_hdawg.ipynb
                    - how-to-guides/sources/01_superconducting_qubits/02_pulse_sequences/01_tuneup/14_Ramsey_experiment_sampled_pulse_shfsg_shfqa_shfqc_hdawg.ipynb
                    - how-to-guides/sources/01_superconducting_qubits/02_pulse_sequences/01_tuneup/15_Flux_dependent_qubit_spectroscopy_shfsg_shfqa_shfqc_hdawg.ipynb
                    - how-to-guides/sources/01_superconducting_qubits/02_pulse_sequences/01_tuneup/16_Flux_scope_experiment_shfsg_shfqa_shfqc_hdawg.ipynb
                    - how-to-guides/sources/01_superconducting_qubits/02_pulse_sequences/01_tuneup/17_Cryoscope_experiment_shfsg_shfqa_shfqc_hdawg.ipynb
                - Advanced Qubit Experiments:
                    - how-to-guides/sources/01_superconducting_qubits/02_pulse_sequences/02_advanced_qubit_experiments/00_active_qubit_reset_hdawg_uhfqa.ipynb
                    - how-to-guides/sources/01_superconducting_qubits/02_pulse_sequences/02_advanced_qubit_experiments/00_active_qubit_reset_shfsg_shfqa_shfqc.ipynb
                    - how-to-guides/sources/01_superconducting_qubits/02_pulse_sequences/02_advanced_qubit_experiments/01_randomized_benchmarking.ipynb
                    - how-to-guides/sources/01_superconducting_qubits/02_pulse_sequences/02_advanced_qubit_experiments/02_active_qudit_reset_shfsg_shfqa_shfqc.ipynb
                    - how-to-guides/sources/01_superconducting_qubits/02_pulse_sequences/02_advanced_qubit_experiments/03_neartime_gate_fidelity_optimization.ipynb
                    - how-to-guides/sources/01_superconducting_qubits/02_pulse_sequences/02_advanced_qubit_experiments/04_parallel_qubit_tuneup_shfqc_hdawg_pqsc.ipynb
            - Workflows:
              - Resonator Spectroscopy: how-to-guides/sources/01_superconducting_qubits/01_workflows/01_resonator_spectroscopy.ipynb
              - Resonator Spectroscopy DC bias: how-to-guides/sources/01_superconducting_qubits/01_workflows/02_resonator_spectroscopy_dcbias.ipynb
              - Qubit spectroscopy: how-to-guides/sources/01_superconducting_qubits/01_workflows/03_qubit_spectroscopy.ipynb
              - Amplitude Rabi: how-to-guides/sources/01_superconducting_qubits/01_workflows/04_amplitude_rabi.ipynb
              - Ramsey interferometry: how-to-guides/sources/01_superconducting_qubits/01_workflows/05_ramsey.ipynb
              - DRAG pulse characterization: how-to-guides/sources/01_superconducting_qubits/01_workflows/06_drag_q_scaling.ipynb
              - Lifetime_measurement: how-to-guides/sources/01_superconducting_qubits/01_workflows/07_lifetime_measurement.ipynb
              - Echo: how-to-guides/sources/01_superconducting_qubits/01_workflows/08_echo.ipynb
              - Amplitude Fine: how-to-guides/sources/01_superconducting_qubits/01_workflows/09_amplitude_fine.ipynb
              - Dispersive Shift: how-to-guides/sources/01_superconducting_qubits/01_workflows/10_dispersive_shift.ipynb
              - IQ blobs: how-to-guides/sources/01_superconducting_qubits/01_workflows/11_iq_blobs.ipynb
              - Raw Time Traces for Optimal Readout Weights: how-to-guides/sources/01_superconducting_qubits/01_workflows/12_time_traces.ipynb
        - Spin Qubits:
          - how-to-guides/sources/02_spin_qubits/index.md
          - how-to-guides/sources/02_spin_qubits/00_neartime_callback_sweeps.ipynb
          - how-to-guides/sources/02_spin_qubits/01_QCoDeS_sweeps.ipynb
          - how-to-guides/sources/02_spin_qubits/02_MFLI_cw_acquisition.ipynb
          - how-to-guides/sources/02_spin_qubits/03_UHFLI_pulsed_acquisition.ipynb
          - how-to-guides/sources/02_spin_qubits/04_HDAWG_pulse_sequences.ipynb
        - Color Centers:
          - how-to-guides/sources/03_color_centers/index.md
          - how-to-guides/sources/03_color_centers/00_shfsg_basic_experiments.ipynb
        - OpenQASM: 
          - how-to-guides/sources/04_qasm/index.md
          - how-to-guides/sources/04_qasm/01_VQE_Qiskit.ipynb
          - how-to-guides/sources/04_qasm/02_RandomizedBenchmarking_from_Qiskit.ipynb
    - API Reference:
      - reference/index.md
      - core:
          - reference/core/index.md
          - validation: reference/core/validation.md
      - experiments:
          - reference/experiments/index.md
          - resonator_spectroscopy: reference/experiments/resonator_spectroscopy.md
          - resonator_spectroscopy_amplitude: reference/experiments/resonator_spectroscopy_amplitude.md
          - qubit_spectroscopy: reference/experiments/qubit_spectroscopy.md
          - qubit_spectroscopy_amplitude: reference/experiments/qubit_spectroscopy_amplitude.md
          - amplitude_rabi: reference/experiments/amplitude_rabi.md
          - ramsey: reference/experiments/ramsey.md
          - lifetime_measurement: reference/experiments/lifetime_measurement.md
          - echo: reference/experiments/echo.md
          - drag_q_scaling: reference/experiments/drag_q_scaling.md
          - amplitude_fine: reference/experiments/amplitude_fine.md
          - dispersive_shift: reference/experiments/dispersive_shift.md
          - iq_blobs: reference/experiments/iq_blobs.md
          - time_traces: reference/experiments/time_traces.md
          - options: reference/experiments/options.md
      - analysis:
          - reference/analysis/index.md
          - resonator_spectroscopy: reference/analysis/resonator_spectroscopy.md
          - qubit_spectroscopy: reference/analysis/qubit_spectroscopy.md
          - amplitude_rabi: reference/analysis/amplitude_rabi.md
          - ramsey: reference/analysis/ramsey.md
          - lifetime_measurement: reference/analysis/lifetime_measurement.md
          - echo: reference/analysis/echo.md
          - drag_q_scaling: reference/analysis/drag_q_scaling.md
          - amplitude_fine: reference/analysis/amplitude_fine.md
          - dispersive_shift: reference/analysis/dispersive_shift.md
          - iq_blobs: reference/analysis/iq_blobs.md
          - time_traces: reference/analysis/time_traces.md
          - calibration_traces_rotation: reference/analysis/calibration_traces_rotation.md
          - fitting_helpers: reference/analysis/fitting_helpers.md
          - plotting_helpers: reference/analysis/plotting_helpers.md
      - contrib:
          - reference/contrib/index.md
          - experiments:
              - reference/contrib/experiments/index.md
              - amplitude_rabi_chevron: reference/contrib/experiments/amplitude_rabi_chevron.md
              - time_rabi: reference/contrib/experiments/time_rabi.md
              - time_rabi_chevron: reference/contrib/experiments/time_rabi_chevron.md
              - signal_propagation_delay: reference/contrib/experiments/signal_propagation_delay.md
              - single_qubit_randomized_benchmarking: reference/contrib/experiments/single_qubit_randomized_benchmarking.md
              - spin_locking: reference/contrib/experiments/spin_locking.md
          - analysis:
              - reference/contrib/analysis/index.md
              - amplitude_rabi_chevron: reference/contrib/analysis/amplitude_rabi_chevron.md
              - time_rabi: reference/contrib/analysis/time_rabi.md
              - time_rabi_chevron: reference/contrib/analysis/time_rabi_chevron.md
              - signal_propagation_delay: reference/contrib/analysis/signal_propagation_delay.md
              - single_qubit_randomized_benchmarking: reference/contrib/analysis/single_qubit_randomized_benchmarking.md
      - qpu_types:
          - reference/qpu_types/index.md
          - tunable_transmon: reference/qpu_types/tunable_transmon.md
      - tasks:
          - reference/tasks/index.md
          - parameter_updating: reference/tasks/parameter_updating.md
      - testing: reference/testing.md
      - typing: reference/typing.md

plugins:
  mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    handlers:
      python:
        import: ["http://qccs.pages.zhinst.com/qccs/manual/objects.inv"]
  mkdocs-jupyter:
    execute: true
  spellcheck:
    known_words: ../known_words.txt
  zhinst-standalone:
    projects:
      - qccs/qccs
    replace: {
      "http://qccs.pages.zhinst.com/qccs/manual": "/qccs/qccs",
    }
